### ISSUE TITLE
How to access our SQLite DB

### ISSUE THREAD

**Issue by CS9490** [SCBSSS/SCBSSS#6]
Hi guys,

Just wanted to give you all a small tutorial on how to access our database from the code I recently pushed to my branch (cris_week1). NOTE: This tutorial is for if you are using an Android simulation. The steps may slightly differ if you are using an iOS simulation.

First, make sure you update your dependencies with 'flutter pub get' in the terminal. Then, run the application and let it load up. Once it's started you can stop the application from running. Note: Don't shut off the phone simulation, only the SCBSSS application. Do this by clicking the red STOP button at the top of Android Studio:
<img width="868" alt="Screenshot 2024-02-08 at 12 11 27 PM" src="https://github.com/SCBSSS/SCBSSS/assets/135974225/6c9e2757-a81f-43a0-958a-a79f44005f64">

What you need to do next is locate the Device Manager tab on Android Studio, locate the device that you used to start the application on (and that is (hopefully) still running), hover over it, and click the three vertical dots on the side of the device you used.

<img width="541" alt="Screenshot 2024-02-08 at 12 12 39 PM" src="https://github.com/SCBSSS/SCBSSS/assets/135974225/294d4fcb-b7ad-427b-aef4-d932769bf433">

Then, click Open in Device Explorer in the drop down menu, and then you will see a bunch of files.

The database file is located at this path: /data/data/com.example.scbsss/app_flutter/scbsss_db.db

Right click that file and click 'Save As...'

Save it in a separate location for easy reference. Once that is done, I recommend downloading SQLite Browser: https://sqlitebrowser.org/dl/

Download that, open the application, and then open up the scbsss_db.db file to see the tables we have. 

If you play around with SQLite Browser, you will see that you can actually do a lot with it, like execute insert, update, or delete operations, modify our schema, and more, in a very straightforward way. This is primarily why I recommend downloading it.

If you want to test on the database directly within the application so that when the app starts you see the changes you made on SQLite Browser, you will need to open the .db file directly in your simulation devices' folder, which again, is at this path, starting at your simulation device's directory: /data/data/com.example.scbsss/app_flutter/scbsss_db.db

Good luck and let me know if you need any help!

Best,
CS

**Comment by CS9490** [comment]
Just as a note, yes, the database is stored locally on each device. We'll be sorting out how to handle all this in the coming days. This is enough to get started on developing our tracking features while me and a few others on our team iron out our database kinks.

Cheers,
CS

**Comment by armyf35** [comment]
@CS9490 Just made a [wiki](https://github.com/SCBSSS/SCBSSS/wiki/How-to-access-our-SQLite-DB) page with this information. So you can close the issue

**Comment by CS9490** [comment]
> @CS9490 Just made a [wiki](https://github.com/SCBSSS/SCBSSS/wiki/How-to-access-our-SQLite-DB) page with this information. So you can close the issue

Thanks :D
